### ISSUE TITLE
Introduce crawl config file

### ISSUE THREAD

**Issue by kdzwinel** [duckduckgo/tracker-radar-collector#35]
We already have a ton of options surfaced to the console and we need to add even more (https://github.com/duckduckgo/tracker-radar-collector/pull/33). It's time to introduce config files (e.g. `npm run crawl -- -c config.js).

**Comment by gunesacar** [comment]
Dear Konrad,

Would it be possible for the Tracker Radar Collector to accept `MAX_LOAD_TIME` as a parameter from outside, or should we wait for this issue to be fixed?

Here's the background:
@StotoV, a brilliant master student at Radboud University, is using Tracker Radar Collector to build an SRI checker tool:
https://github.com/StotoV/sri-checker

His tool uses Radar Collector as a module, and adds new collectors that he developed:
https://github.com/StotoV/sri-checker/blob/d2f6239424d8d21a7716719e5896b5adf8c68b35/src/scrape.js#L7-L8

Unfortunately, certain online SRI test suites take very long to load, resulting in a timeout due to [`MAX_LOAD_TIME`](https://github.com/duckduckgo/tracker-radar-collector/blob/c44275829ec55e4a5f4e3bbedc7959171823097b/crawler.js#L8).
That's why he was wondering if it'd be possible to configure `MAX_LOAD_TIME` from outside.

Let me know if anything is unclear. Thanks so much.

**Comment by kdzwinel** [comment]
Hey @gunesacar, yes absolutely, this should not be hardcoded. I'll look into this once we get https://github.com/duckduckgo/tracker-radar-collector/pull/57 merged.

@StotoV your tool looks great, nicely done!

**Comment by kdzwinel** [comment]
Config file will be introduced with #58 . I haven't made that value configurable yet, but it's still on my radar. Moved this particular issue to https://github.com/duckduckgo/tracker-radar-collector/issues/59.

**Comment by gunesacar** [comment]
Thanks so much @kdzwinel

**Comment by kdzwinel** [comment]
Sure thing! Both this and #59 are now fixed, so hopefully I unblocked you. Keep the feedback coming :)
